### ISSUE TITLE
Registration UX bug (password field)

### ISSUE THREAD

**Issue by skywinder** [matterinc/PeepethClient#5]
![3e2873fb-fffd-4ec9-99d9-0d118311700e](https://user-images.githubusercontent.com/3356474/45251290-d1de7d00-b343-11e8-815c-894038edeecc.png)
Password doesn’t match label says before finishing input of second password field.

**Comment by WildStudio** [comment]
Hi! Can I assign this to me? We are hosting a Hacktoberfest, and I am choosing some small things that can be done during the event. So I would like to take this one. Thanks

**Comment by BaldyAsh** [comment]
@WildStudio hi! Sure, you've been assigned

**Comment by BaldyAsh** [comment]
Closed by PR #21
